name: Build

on:
  workflow_run:
    workflows: ["Check Formatting"]
    types:
      - completed

jobs:
  build:
    name: Build
    runs-on: darwin-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v4
      name: Set up Go

    - uses: actions/setup-go@v5
      with:
        go-version: ^1.22

    - name: Build
      run: go build -v ./...

    - name: Install
      run: go install -v ./...

    - name: Check the build
      run: |
        TARGET=$(go env GOPATH)/bin
        if [[ ":$PATH:" != *":$TARGET:"* ]]; then
          echo "$TARGET is not in PATH"
          exit 1
        fi
      shell: bash
