name: Release

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  check_tag:
    runs-on: ubuntu-latest
    outputs:
      is_version_tag: ${{ steps.tag_check.outputs.is_version_tag }}
    steps:
      - name: Get the tag name from workflow_run
        id: get_tag
        run: |
          echo "TAG_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          echo "Ref: $GITHUB_REF"

      # Assuming GITHUB_REF_NAME or another variable is correctly set to the tag name,
      # we then check if the tag matches the semantic version pattern.
      - name: Check if tag is a version tag
        id: tag_check
        run: |
          if [[ "${{ env.TAG_NAME }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+.*$ ]]; then
            echo "is_version_tag=true" >> $GITHUB_ENV
          else
            echo "is_version_tag=false" >> $GITHUB_ENV
          fi
        env:
          TAG_NAME: ${{ github.event.workflow_run.head_commit.message }}

  release:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          # build and publish in parallel: linux/amd64, linux/arm64, darwin/amd64, darwin/arm64
          goos: [linux, darwin]
          goarch: [amd64, arm64]

      steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://go.dev/dl/go1.22.0.linux-arm64.tar.gz"
